#skip_non_tags: true
build_cloud: Docker
image: minimal-windowsservercore-ltsc2019

environment:
    matrix:
        - PLATFORM: x64
          NODEJS_VERSION: "8"
          RUST_TOOLCHAIN: stable-x86_64-pc-windows-msvc
        - PLATFORM: x64
          NODEJS_VERSION: "10"
          RUST_TOOLCHAIN: stable-x86_64-pc-windows-msvc

install:
    - ps: Install-Product node $env:NODEJS_VERSION $env:PLATFORM
    - npm config set msvs_version 2017
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe -y --default-toolchain %RUST_TOOLCHAIN%
    - npm install

build_script:
    - node ./prepare.js
