skip_non_tags: true
build_cloud: Docker

environment:
    NODE_PRE_GYP_GITHUB_TOKEN:
        secure: 03IxabmXiMYR8n/pfRgM3jFl1CgyLHYmlk2tLORdnmZ8WBs6jqxIbkPSSSThDCDj
    matrix:
        - docker_image: genjio/neon:10
        - docker_image: genjio/neon:12
        - docker_image: genjio/neon_l:10
        - docker_image: genjio/neon_l:12

build_script:
    - npm install neon-cli
    - node ./prepare.js

on_success:
    - npm install node-pre-gyp-github
    - npm run package
    - npm run gpublish
